# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters (balanced set)
    - bodyclose
    - durationcheck
    - gofmt
    - goimports
    - misspell

  disable:
    # Disabled for initial pass - too strict
    - godot # Comments must end with period
    - gocritic # Very opinionated
    - revive # Naming stutters etc
    - errorlint # Wrapped errors comparison
    - gosec # Security - will enable later
    - nilnil # nil, nil returns
    - prealloc # Slice preallocation
    - dupl # Code duplication
    - gocognit # Cognitive complexity
    - gocyclo # Cyclomatic complexity
    - goconst # Repeated strings
    - nakedret # Naked returns
    - unparam # Unused parameters
    - whitespace # Whitespace issues
    - stylecheck # Style checks
    - nolintlint # nolint directives
    - tparallel # t.Parallel usage

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - io.Copy
      - (io.Closer).Close
      - os.Remove
      - os.RemoveAll

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/streaming-service

issues:
  exclude-dirs:
    - vendor
    - bin
    - deployments

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Allow blank identifier for intentionally ignored errors
    - linters:
        - errcheck
      text: "Error return value of .* is not checked"
      source: "^\\s*_\\s*="

  max-issues-per-linter: 50
  max-same-issues: 10
